CREATE TABLE player_total_stats (
	season_id INT NOT NULL,
    season INT NOT NULL,
    player_id INT NOT NULL,
    player_name VARCHAR(255),
    pos VARCHAR(15),
    abbreviation VARCHAR(5),
    game_played INT,
    minutes_played INT,
    fg INT,
    fga INT,
    fg_percent double,
    x3p_percent double,
    x2p_percent double,
    ft INT,
    fta INT,
    ft_percent double,
    orb INT,
    drb INT,
    trb INT,
    ast INT,
    stl INT,
    blk INT,
    pts INT,
    primary KEY (season_id),
    FOREIGN KEY (player_id) REFERENCES player_info(player_id)
);
