CREATE TABLE team_total_stats (
    season INT,
    team_name VARCHAR(63),
    abbreviation VARCHAR(4),
    playoffs BOOLEAN,
    game_played INT,
    minutes_played INT,
    fg INT,
    fga INT,
    fg_percent double,
    x3p INT,
    x3pa INT,
    x3p_percent double,
    x2p INT,
    x2pa INT,
    x2p_percent double,
    ft INT,
    fta INT,
    ft_percent double,
    orb INT,
    drb INT,
    trb INT,
    ast INT,
    stl INT,
    blk INT,
    tov INT,
    pf INT,
    pts INT
);

